version: "3.9"

services:
  kick-miner:
    image: kick-channel-points-miner
    build:
      context: .
      dockerfile: Dockerfile

    container_name: kick-miner
    restart: unless-stopped

    volumes:
      - ${CONFIG_FILE:-./config.json}:/app/config.json:ro

    ports:
      - "5000:5000"

    environment:

      - PYTHONUNBUFFERED=1
